name: Teste de Performance e Deploy para GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Instalar JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "$(pwd)/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

      - name: Executar Testes
        run: |
          mkdir -p results/dashboard
          jmeter -n -t ./scripts/script.jmx -l ./results/log.jtl -e -o ./results/dashboard -f

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Aponta para a pasta onde o index.html do JMeter foi gerado
          path: './results/dashboard'

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
